name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Packages and Boost
      run: sudo apt-get update && sudo apt-get install -yq sendmail gnutls-dev libboost-dev libboost-system-dev libcurl4-gnutls-dev nlohmann-json3-dev

    - name: BuildProject
      run: mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=../dist .. && make -j9 && cd ..

    - name: Install Project
      run: cd build && make install

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: dist/*
